from datetime import datetime
from os import getcwd

time = datetime.now().strftime("%d-%m-%y | %H:%M:%S | ")
BASE_DIR = getcwd()
UPLOADCSV = r"UPLOADS\DOWNLOAD_RELATORIOS\csv"
UPLOADXLSX = r"UPLOADS\DOWNLOAD_RELATORIOS\xlsx"
UPLOAD_PROCESSADO = r'UPLOADS\UPLOAD_RELATORIOS\UPLOAD_PROCESSADOS' 
RELATORIO = r"UPLOADS\UPLOAD_RELATORIOS"
LOG = r"codigo\LOG"
ERROR_LOG = r"codigo\LOG\error.log"
HISTORICO = r'UPLOADS\DOWNLOAD_RELATORIOS\xlsx\HISTORICO'